mysql:
  host: localhost
  port: 3306
  user: root
  password: luxiel123
  database: EchoMC
  table: EchoBan
banmessage: '&cBanned by %punisher% for %period%'
mutemessage: '&cMuted by %punisher% for %period%'